<div class="col-sm-12 packages">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-10">
        <h2 class="payment-title">Edit Profile</h2>

        <?php $form_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'edit-profile'), 'default', true); ?>
        <form role="form"  method="POST" class="centered" id="edit_profile_form" action="<?php echo $form_url?>" >
              
            <div class="form-group">
                <label class="label-payment-form">Email</label>
                <input type="email" class="form-control" name="<?php echo $one->name?>" required=true/>
            </div>

            <div class="form-group">
                <label class="label-payment-form">Password</label>
                <input type="password" class="form-control" name="<?php echo $one->name?>" required=true/>
            </div>
            
            <div class="form-group">
                <label class="label-payment-form">Repeat password</label>
                <input type="password" class="form-control" name="<?php echo $one->name?>" required=true/>
            </div>

            <button type="submit" name="<?php echo $one->name?>" id="register_form_button" class="form-control btn btn-primary btn-block">Save profile information <i class="glyphicon glyphicon-arrow-right"></i>
                </button>
                
        </form>
    </div>
    <div class="col-sm-1">
    </div>
</div>
