<div class="user">
    <div class="main-content">
        <div class="col-sm-12">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-10">
                <h2 class="payment-title">Edit Profile</h2>

                <?php $form_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'edit-profile'), 'default', true); ?>
                <form role="form"  method="POST" class="centered" id="edit_profile_form" action="<?php echo $form_url?>" >
                      
                    <div class="form-group">
                        <label class="label-payment-form">Email</label>
                        <p class="form-control-static"><?php echo $this->user['email']; ?></p>
                    </div>

                    <div class="form-group">
                        <label class="label-payment-form">Password</label>
                        <input type="password" class="form-control" name="password" id="password" required=true/>
                    </div>
                    
                    <div class="form-group">
                        <label class="label-payment-form">Repeat password</label>
                        <input type="password" class="form-control" name="re_password" required=true/>
                    </div>

                    <button type="submit" id="register_form_button" class="form-control btn btn-primary btn-block">Save profile information <i class="glyphicon glyphicon-arrow-right"></i>
                        </button>
                        
                </form>
            </div>
            <div class="col-sm-1">
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function($){  
    
        $('#edit_profile_form').submit(function(e){
            var isvalidate = $("#edit_profile_form").valid();
            if(!isvalidate){
              e.preventDefault();
            }
        })

        $('#edit_profile_form').validate({
            rules: {
                password : {
                    required: true,
                    minlength: 5,
                    maxlength: 10
                },
                re_password: {
                  equalTo: "#password"
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('success').addClass('error');
            },
            unhighlight: function(element) {
                $(element).closest('.form-group').removeClass('error').addClass('success');
            },
            success: function (element) {
                element.addClass('valid')
                    .closest('.form-group').removeClass('error').addClass('success');
            }
        });
    });
</script>
