<div class="col-sm-12 forgotten-password">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-10">
    	<?php $form_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'forgotten-password'), 'default', true); ?>
		<form role="form"  method="POST" class="forgotten-password-form" id="forgotten-password-form" action="<?php echo $form_url?>">
		<h2 class="change-password-title">Retrieve Password</h2>
			<div class="form-group">
			<label>Your email</label>
				<input type="email" class="form-control" name="email" id="email" value="" placeholder="Email"/>
			</div>
			<div class="form-group">
				<button type="submit" name="forgotten-password-submit" class="btn btn-primary btn-block forgotten-password-submit">Retrieve <i class="glyphicon glyphicon-arrow-right"></i>
				</button>
			</div>
		</form>
	</div>
	<div class="col-sm-1">
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function($){  
        
        $('#forgotten-password-form').submit(function(e){
            var isvalidate = $("#forgotten-password-form").valid();
            if(!isvalidate){
              e.preventDefault();
            }
        })

        $('#forgotten-password-form').validate({
            rules: {
                email: {
                	required: true,
                    email: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('success').addClass('error');
            },
            unhighlight: function(element) {
                $(element).closest('.form-group').removeClass('error').addClass('success');
            },
            success: function (element) {
                element.addClass('valid')
                    .closest('.form-group').removeClass('error').addClass('success');
            }
        });
    });
</script>