<div class="col-sm-12 packages">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-10">
        <h2 class="payment-title">Profile</h2>

        <h4 class="user-title">info</h4>

        <form class="form-horizontal view-profile" role="form">
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Email:</label>
                <div class="col-sm-10">
                <p class="form-control-static"><?php echo $this->user->email; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="pwd">Password:</label>
                <div class="col-sm-10">          
                <p class="form-control-static" id="pwd"><?php echo $this->user->password; ?></p>
                </div>
            </div>
            <div class="form-group">        
                <div class="col-sm-12">
                <a class="form-control btn btn-primary btn-block" href="/user/edit-profile">Edit profile</a>
                </div>
            </div>
        </form>
    </div>
    <div class="col-sm-1">
    </div>
</div>