<div class="user">
    <div class="main-content">
        <div class="col-sm-12">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-10">
                <h2 class="payment-title">Profile</h2>

                <h4 class="user-title">info</h4>

                <form class="form-horizontal view-profile" role="form">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="email">Email:</label>
                        <div class="col-sm-10">
                        <p class="form-control-static"><?php echo $this->user->email; ?></p>
                        </div>
                    </div>
                    <div class="form-group">        
                        <div class="col-sm-12">
                        <a class="form-control btn btn-primary btn-block" href="/user/edit-profile">Edit profile</a>
                        </div>
                    </div>
                                
                </form>

                <?php if(isset($this->user->payment_type_id)){ ?>
                    <h4 class="user-title">Your subscriptions:</h4>
                    <div class="subscriptions-holder">
                        <?php foreach($this->cc_sub_packages as $one){ 
                            if($one->id == $this->package_id_clicked){?>
                                <div class="cc-sub-packages">
                                    <a href="#"><img src="<?php echo $one->img; ?>" width="100%"></a>
                                    <a href="/user/cancel-subscription" class="cancel-subscription">Cancel subscription</a>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
            <div class="col-sm-1">
            </div>
        </div>
    </div>
</div>