<div class="col-sm-12 packages">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-10">
        <h2 class="payment-title">Register</h2>
        <?php $form_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'register'), 'default', true); ?>
        <form role="form"  method="POST" class="centered" id="register_form" action="<?php echo $form_url?>" >
            <input type="hidden" id="hidden_package_id" name="hidden_package_id" value="<?php echo $this->package_id;?>">
        <?php foreach(json_decode($this->app_settings->submit_register_form) as $one){ ?>
            <?php if($one->type == 'button'){?>
                
                <button type="submit" name="<?php echo $one->name?>" id="register_form_button" class="form-control btn btn-primary btn-block"><?php echo $one->label?> <i class="glyphicon glyphicon-arrow-right"></i>
                </button>
            <?php } else if($one->type == 'password'){?>
            <div class="form-group">
                <label class="label-payment-form"><?php echo $one->label;?></label>
                <input type="password" class="form-control" name="<?php echo $one->name?>" id="<?php echo $one->name?>" required="<?php echo $one->required;?>"/>
            </div>
            <?php }else{?>
            <div class="form-group">
                <label class="label-payment-form"><?php echo $one->label;?></label>
                <input type="text" class="form-control" name="<?php echo $one->name?>" required="<?php echo $one->required;?>"/>
            </div>
            <?php }?>
        <?php } ?>
        </form>
    </div>
    <div class="col-sm-1">
    </div>
    
    <div class="existing-user">
	    <div class="col-sm-1">
	    </div>
	    <div class="col-sm-10">
	    	<h2>Existing User</h2>
	    	<a href="/user/login" class="form-control btn btn-primary btn-block">Procead to login <i class="glyphicon glyphicon-arrow-right"></i></a>
	    </div>
	    <div class="col-sm-1">
    	
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function($){  
        $('.label-payment-form').each(function(){
            var text = $(this).text().split('-');
            var last = text.pop();
            var result =  text.join(" ") + (text.length > 0 ? '<span class="last">'+ '-' + last+'</span>' : last); 
            $(this).html(result);
        })

        $('#register_form').submit(function(e){
            var isvalidate = $("#register_form").valid();
            if(!isvalidate){
              e.preventDefault();
            }
        })

        $('#register_form').validate({
            rules: {
                email: {
                    required: true,
                    email: true
                },
                password : {
                    required: true
                },
                re_password: {
                  equalTo: "#password"
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('success').addClass('error');
            },
            unhighlight: function(element) {
                $(element).closest('.form-group').removeClass('error').addClass('success');
            },
            success: function (element) {
                element.addClass('valid')
                    .closest('.form-group').removeClass('error').addClass('success');
            }
        });
    });
</script>