<div class="col-sm-12 forgotten-password">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-10">
    	<?php $form_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'reset-password'), 'default', true); ?>
		<form role="form"  method="POST" class="forgotten-password-form" id="reset-password-form" action="<?php echo $form_url?>" autocomplete="off">
		<h2 class="change-password-title">Reset Password</h2>
			<div class="form-group">
			<label>Your code</label>
				<input type="text" class="form-control" name="code" id="code" value="" placeholder="Your code"/>
			</div>
			<div class="form-group">
			<label>Password</label>
				<input type="password" class="form-control" name="password" id="password" value="" placeholder="Password"/>
			</div>
			<div class="form-group">
			<label>Repeat password</label>
				<input type="password" class="form-control" name="re_password" id="re_password" value="" placeholder="Repeat password"/>
			</div>
			<div class="form-group">
				<button type="submit" name="forgotten-password-submit" class="btn btn-primary btn-block forgotten-password-submit">Save <i class="glyphicon glyphicon-arrow-right"></i>
				</button>
			</div>
		</form>
	</div>
	<div class="col-sm-1">
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function($){  
        
        $('#reset-password-form').submit(function(e){
            var isvalidate = $("#reset-password-form").valid();
            if(!isvalidate){
              e.preventDefault();
            }
        })

        $('#reset-password-form').validate({
            rules: {
            	code : {
            		textonly: true,
                    required: true
                },
                password : {
                    required: true
                },
                re_password: {
                	required: true,
                  	equalTo: "#password"
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('success').addClass('error');
            },
            unhighlight: function(element) {
                $(element).closest('.form-group').removeClass('error').addClass('success');
            },
            success: function (element) {
                element.addClass('valid')
                    .closest('.form-group').removeClass('error').addClass('success');
            }
        });
        $.validator.addMethod( "textonly", function(value, element){
		    valid = false;
		    check = /[^-\.a-zA-Z\s\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02AE]/.test(value);
		    if(check==false)
		        valid = true;
		    return this.optional(element) || valid;
		}, 
		$.validator.format("Please only enter letters, spaces, periods, or hyphens.")
		);
    });
</script>