<div class="welcome">

	<div class="col-sm-12 android-page" align="center">
		<div class="welcome-button">
			<a href="#">
				<img src="/images/button.png" width="100%">
			</a>
		</div>
	</div>
	<div class="col-sm-12 android-page link-mobile" align="center">
		<?php $no_android_url = $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default', true);?>
		<a href="<?php echo $no_android_url;?>" > nastavi na mobile sajt</a>
	</div>
	
</div>