<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
	    <title><?php echo Zend_Registry::get('app_name')?></title>

		<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css">
		<link href="/css/header.css" rel="stylesheet">
		<link rel="stylesheet" href="/css/custom.css" type="text/css">
	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
	    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  	</head>
  <body class="android">
		<div class="desktop-view">
			Stranica je namenjena poseti samo sa mobilnih uredjaja.
		</div>
	</body>
</html>

