<?php //var_dump($this->user);die; ?>
<?php foreach($this->featured_content as $index => $one){ 
    $class = $index > $this->app_settings->first_x_big_thumbs_contents-1  && $index% 2 == 0 ? '' : 'odd';
    $video_url = $this->url(array('module' => 'default', 'controller' => 'content', 'action' => 'video', 'id' => $one->id,'cat_id' => 0), 'default', true);
    if($index < $this->app_settings->first_x_big_thumbs_contents) {?>
        <div class="col-md-12 no-padding">
            <div class="row holder">
                <a href="<?php echo $video_url;?>" class="video-link">
                    <div class="img-container">
                        <div class="duration-holder"><?php echo $one->view_count.' views'; ?></div>
                        <img class="video-image" src="<?php echo $one->thumb_url; ?>">
                        <p class='content-title'><?php echo $one->title; ?></p>
                        <p class='content-raiting color'>
                            <input id="fake-rating" type="number" class="rating smallest" min=0 max=5 step=1 value=<?php echo $one->rating?> data-size="sm">
                        </p>
                        <div class="play"></div>
                        <div class="tags-stream">
                        <?php foreach(explode(',', $one->tags) as $one_tag){?>
                            <span class="label label-default"><?php echo $one_tag;?></span>
                        <?php }?>
                    </div>
                    </div> 
                </a>
            </div>
        </div>

    <?php }else{ ?>
        <div class="col-md-12 no-padding">
            <div class="row holder <?php echo $class;?>">
                <div class="left-part">
                    <a href="<?php echo $video_url;?>" class="video-link">
                        <img class="video-image" src="<?php echo $one->thumb_url; ?>">
                        <div class="play small"></div>
                    </a>
                </div>
                <div class="right-part">
                    <a class="title-holder" href="<?php echo $video_url; ?>">
                        <p><?php echo $one->title; ?></p>
                    </a>
                    <div class="stars-holder">
                        <input id="fake-rating" type="number" class="rating smallest" min=0 max=5 step=1 value=<?php echo $one->rating?> data-size="xs">
                    </div>
                    <div class="views-holder">
                        <span class="video-date"><?php echo $one->view_count.' views';?></span>
                    </div>
                </div>
            </div>
        </div>
    <?php }?>
<?php } ?>

