<?php foreach($this->featured_content as $index => $one){ 
    $class = $index > $this->app_settings->first_x_big_thumbs_contents-1  && $index% 2 == 0 ? '' : 'odd';
    $stream_url = $this->url(array('module' => 'default', 'controller' => 'content', 'action' => 'stream', 'id' => $one->id), 'default', true); 
    if($index < $this->app_settings->first_x_big_thumbs_contents) {?>
        <div class="col-md-12 no-padding">
            <div class="row holder">
                <a href="<?php echo $stream_url;?>" class="video-link">
                    <div class="img-container">
                        <div class="badge badge-duration"><?php echo $one->view_count.' views'; ?></div>
                        <img class="video-image" src="<?php echo $one->thumb_url; ?>">
                        <p class='content-title'><?php echo $one->title; ?></p>
                        <div class="play"></div>
                        <div class="tags-stream video-info-tags">
                        <?php foreach(explode(',', $one->tags) as $one_tag){?>
                            <span class="label label-default"><?php echo $one_tag;?></span>
                        <?php }?>
                    </div>
                    </div> 
                </a>
            </div>
        </div>

    <?php }else{ ?>
        <div class="col-md-12 no-padding">
            <div class="row holder <?php echo $class;?>">
                <div class="col-sm-5 col-xs-5 img-container">
                    <a href="<?php echo $stream_url;?>" class="video-link">
                        <img class="video-image" src="<?php echo $one->thumb_url; ?>">
                        <!--div class="badge badge-duration"><?php //echo gmdate("H:i:s", $video->duration);?></div-->
                        <div class="play small"></div>
                    </a>
                </div>
                <div class="col-sm-7 col-xs-7">
                    <div class="col-xs-12">
                        <a class="video-link" href="<?php echo $stream_url; ?>">
                            <p class="video-info-title"><?php echo $one->title; ?></p>
                        </a>
                    </div>
                    <div class="col-xs-12 video-info-tags">
                        <?php foreach(explode(',', $one->tags) as $one_tag){?>
                            <span class="label label-default"><?php echo $one_tag;?></span>
                        <?php }?>
                    </div>
                    <div class="col-xs-12">
                        <span class="video-date"><?php echo $one->view_count.' views';?></span>
                    </div>
                </div>
            </div>
        </div>
    <?php }?>
<?php } ?>