<div class="packages-container">
	<?php foreach($this->cc_sub_packages as $one){ ?>
	    <?php 
	        $cc_pack_url = $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'register', 'package_id' => $one->id), 'default', true); 
	    ?>
	    <div class="cc-sub-packages"><a href="<?php echo $cc_pack_url;?>"><img src="<?php echo $one->img; ?>" width="100%"></a></div>
	<?php } ?>
</div>

<!-- begin SIGN UP NOW BUTTON, start copying here -->
<form action="https://secure.verotel.com/order" method="GET">
	<input type=hidden name=website value="104780">
	<center>
		<input type="image" src="http://buttons.verotel.com/join/button_002402104780.gif" alt="Signup NOW!">
		<img src="http://buttons.verotel.com/signup/tbutton_104780.gif" border="0" width="1" height="1" alt="">
	</center>
</form>
<!-- end SIGN UP NOW BUTTON, end copying here -->