<div class="col-sm-12 packages-container">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-10">
        <?php $form_url = $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'register'), 'default', true); ?>
        <form name="form" method="POST" class="centered" id="register_form" action="<?php echo $form_url?>" onsubmit="return validateForm()">
            <input type="hidden" id="hidden_package_id" name="hidden_package_id" value="<?php echo $this->package_id;?>">
        <?php foreach(json_decode($this->app_settings->submit_form_elements) as $one){ ?>
            <?php if($one->type == 'button'){?>
                <br/>
                <input type="submit" name="<?php echo $one->name?>" id="register_form_button" class="form-control register-inputs button-form" value="<?php echo $one->label?>" required="<?php echo $one->required;?>"><br/>
            <?php } else if($one->type == 'select'){?>
                <span class="label-register-form"><?php echo $one->label;?></span><br/>
                <select dir="rtl" class="form-control register-inputs" name="<?php echo $one->name?>">
                  <option value="srbija">Srbija</option>
                  <option value="crna_gora">Crna Gora</option>
                </select><br/>
            <?php } else if($one->type == 'credit_card_date'){?>
                <span class="label-register-form"><?php echo $one->label;?></span><br/>
                <input type="text" class="form-control register-inputs" data-mask="99/2099" placeholder="mm/yyyy" data-type="<?php echo $one->type;?>" name="<?php echo $one->name?>" required="<?php echo $one->required;?>"><br/>
            <?php }else{?>
                <span class="label-register-form"><?php echo $one->label;?></span><br/>
                <input type="text" class="form-control register-inputs" data-type="<?php echo $one->type;?>" name="<?php echo $one->name?>" required="<?php echo $one->required;?>"><br/>
            <?php }?>
        <?php } ?>
        </form>
    </div>
    <div class="col-sm-1">
    </div>
</div>