<div class="col-sm-12 packages">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-10">
        <h2 class="payment-title">Payment</h2>
        <?php $form_url = $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'register'), 'default', true); ?>
        <form role="form"  method="POST" class="centered" id="register_form" action="<?php echo $form_url?>" >
            <input type="hidden" id="hidden_package_id" name="hidden_package_id" value="<?php echo $this->package_id;?>">
        <?php foreach(json_decode($this->app_settings->submit_form_elements) as $one){ ?>
            <?php if($one->type == 'button'){?>
                
                <button type="submit" name="<?php echo $one->name?>" id="register_form_button" class="form-control btn btn-primary btn-block"><?php echo $one->label?> <i class="glyphicon glyphicon-arrow-right"></i>
                </button>
            <?php } else if($one->type == 'select'){?>
            <div class="form-group">
                <label class="label-payment-form"><?php echo $one->label;?></label>
                <select  class="form-control" name="<?php echo $one->name?>">
                  <option value="srbija">Srbija</option>
                  <option value="crna_gora">Crna Gora</option>
                </select>
            </div>
            <?php } else if($one->type == 'expiration_month'){?>
            <div class="form-group">
                <label class="label-payment-form"><?php echo $one->label;?></label>

                <select  class="form-control" name="<?php echo $one->name?>" >
                    <option value="0">Month</option>
                    <?php for ($i=1; $i < 13; $i++) { ?>
                        <option value="<?php echo $i?>"><?php echo $i?></option>
                    <?php } ?>
                </select>
            </div>
             <?php } else if($one->type == 'expiration_year'){?>
             <div class="form-group">
                <select  class="form-control" name="<?php echo $one->name?>" >
                    <option value="0">Year</option>
                    <?php for ($i=date('Y'); $i < date('Y')+10; $i++) { ?>
                      <option value="<?php echo $i?>"><?php echo $i?></option>
                    <?php } ?>
                </select>
            </div>
            <?php }else{?>
            <div class="form-group">
                <label class="label-payment-form"><?php echo $one->label;?></label>
                <input type="text" class="form-control" name="<?php echo $one->name?>" />
            </div>
            <?php }?>
        <?php } ?>
        </form>
    </div>
    <div class="col-sm-1">
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function($){  
        $('.label-payment-form').each(function(){
            var text = $(this).text().split('-');
            var last = text.pop();
            var result =  text.join(" ") + (text.length > 0 ? '<span class="last">'+ '-' + last+'</span>' : last); 
            $(this).html(result);
        })

        function isValidExpirationDate(month , year) {
            return !(month === '0' || year ==='0'); 
        }

        $('#register_form').submit(function(e){
            var isvalidate = $("#register_form").valid();
            console.log(isvalidate);
            if(!isvalidate){
              e.preventDefault();
            }else{
                  var month = $('[name=expiration_month]').val();
                  var year = $('[name=expiration_year]').val();
                  var format = isValidExpirationDate( month, year );
                  if(format == false){
                    e.preventDefault();
                    alert("Neispravan format datuma!");
                  }
            }
        })

        $('#register_form').validate({
            rules: {
                first_name: {
                  minlength: 2,
                  required: true
                },
                last_name: {
                  minlength: 2,
                  required: true
                },
                email: {
                    required:true,
                    email: true
                },
                card_number : {
                    required:true,
                    digits: true
                },
                zip_code : {
                    required: true
                }
            },
            errorElement: 'span',
            highlight: function (element) {
                $(element).closest('.form-group').removeClass('success').addClass('error');
            },
            unhighlight: function(element) {
                $(element).closest('.form-group').removeClass('error').addClass('success');
            },
            success: function (element) {
                element.addClass('valid')
                    .closest('.form-group').removeClass('error').addClass('success');
            }
        });
    });
</script>