<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="utf-8">
	    <meta name="viewport" content=" , initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
	    <title><?php echo Zend_Registry::get('app_name')?></title>
		<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic&subset=cyrillic,latin' rel='stylesheet' type='text/css'>

		<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css">
		<link href="/css/jasny-bootstrap.css" rel="stylesheet" type="text/css">
		<link href="/css/header.css" rel="stylesheet" type="text/css">
		<link href="/css/custom.css" rel="stylesheet" type="text/css">
		<link href="/css/star-rating.css" rel="stylesheet" type="text/css">
		<link href="/css/toastr.css" rel="stylesheet" type="text/css">

	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
	    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

	    <script type="text/javascript" src="/js/validate/jquery.validate.js"></script>
        <script type="text/javascript" src="/js/validate/additional-methods.js"></script>
  	</head>
  <body>
  	<!-- Google Tag Manager -->
	<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PHJRLR"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-PHJRLR');</script>
	<!-- End Google Tag Manager -->

	<div class="navmenu navmenu-default navmenu-inverse navmenu-fixed-left offcanvas-md">
		<ul class="nav navmenu-nav">
			<li><a href="/">Home</a></li>
			<?php foreach ($this->categories as $category) { 
				$category_url = $this->url(array('module' => 'default', 'controller' => 'content', 'action' => 'category', 'id' => $category->id), 'default', true); 
				$active_tab = 1;
				$class = ($active_tab == $category->id) ? 'active' : '';
			?>
			<li class="<?php echo $class; ?>"><a href="<?php echo $category_url; ?>"><?php echo $category->title; ?></a></li>
			<?php } ?> 
		</ul>
	</div>

    <div class="navbar navbar-default navmenu-inverse navbar-fixed-top hidden-lg col-md-12">
		<div class="col-xs-2 col-sm-2 col-md-2 no-padding">
			<button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navmenu">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="col-xs-8 col-sm-8 col-md-8">
			<a class="navbar-brand" href="/" ><img class="logo-img" src="/images/fappexxx_logo.png"></a>
		</div>
		<?php 
			$terms_url = $this->url(array('module' => 'default', 'controller' => 'static', 'action' => 'terms'), 'default', true);
			$privacy_url = $this->url(array('module' => 'default', 'controller' => 'static', 'action' => 'privacy'), 'default', true);
			$faq_url = $this->url(array('module' => 'default', 'controller' => 'static', 'action' => 'faq'), 'default', true);
			$customer_support_url = $this->url(array('module' => 'default', 'controller' => 'static', 'action' => 'customer'), 'default', true);

			$login_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'login'), 'default', true); 
			$logout_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'logout'), 'default', true);
			$profile_url = $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'profile'), 'default', true);
			
		?>
		<div class="col-xs-2 col-sm-2 col-md-2 no-padding">
			<ul class="nav navbar-right">
	            <li class="dropdown user-dropdown">
	                <a href="#" class="dropdown-toggle action-icon" data-toggle="dropdown">
	                	<img src="/images/ic_action_overflow.png">
	                </a>
	                <ul class="dropdown-menu">
	                    <li><a href="<?php echo $terms_url;?>">Terms and conditions</a></li>
	                    <li><a href="/index/packages/">Subscribe</a></li>
	                    <?php if ($this->user) { ?>
	                    	<li><a href="<?php echo $profile_url;?>">My profile</a></li>
	                    	<li><a href="<?php echo $logout_url;?>">Logout</a></li>
	                    <?php } else{ ?>
	                    	<li><a href="<?php echo $login_url;?>">Login</a></li>
	                    <?php }?>
	                </ul>
	            </li>
	        </ul>
		</div>

    </div>
    <div class="container layout-holder no-padding">
    	<div id="flash-messanger" style="display:none;"><?php echo $this->flashMessenger(); ?></div>
        <?php echo $this->layout()->content; ?>
    </div> 
    
    <div id="footer" class="fix" >
        <p class="copyRight">
        	Copyright © 2015 xtcprime.com. All rights reserved. See our
			<a href="<?php echo $customer_support_url; ?>">Customer support,</a>
            <a href="<?php echo $privacy_url;?>">privacy policy</a>and
            <a href="<?php echo $terms_url;?>">terms of use.</a><br> 
            <a href="<?php echo $faq_url;?>">18 USC 2257 COMPLIANCE,</a>
            <a href="https://cs.segpay.com/SPSolo.aspx">SegPay Customer Service,</a>
            <a href="http://www.segpay.com/">SegPayEU.</a>
        </p>
    </div>

	<script src="<?php echo $this->baseUrl('/js/toastr.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/flowplayer/flowplayer-3.2.12.min.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/flowplayer/flowplayer.ipad-3.2.12.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/front/videojs.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/strobe/swfobject.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/strobe/ParsedQueryString.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/front/star-rating.min.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/front/custom.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/front/bootstrap.min.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/jasny-bootstrap.min.js'); ?>"></script>

	<div class="navmenu navmenu-default navmenu-fixed-left offcanvas-md offcanvas-clone"></div>
</body>
</html>