<div class="col-md-12 no-padding">
    <div id="webtv" class="fp3"> </div>
    <div class="row holder">
        <div class="video-main-info">
        	<h1 class="video-main-title"><?php echo $this->existing->title;?></h1>
        	<p class="video-main-user">
                Tags:
    			<?php foreach($this->existing->tags as $one_tag){?>
                    <?php echo $one_tag;?></a>
                <?php }?>
    		</p>
    		<span class="video-main-plays"><?php echo $this->existing->view_count ? $this->existing->view_count : '0';?> plays</span>
        </div>
     </div>
</div>
<script>
var content_object = <?php echo json_encode($this->existing);?>;
</script>