<style type="text/css">
	figure {
	max-width:1024px;
	max-width:64rem;
	width:100%;
	height:auto;
	margin:20px 0 0;
	margin:1.25rem 0 0;
}
figcaption {
	display:block;
	font-size:16px;
	font-size:1rem;
}
video {
	width:100%;
	height:auto;
}

/* controls */
.controls, .controls li {
	padding:0;
	margin:0;
}
.controls {
	display:none;
	list-style-type:none;
	overflow:hidden;
	background:transparent;
}
.controls li {
	float:left;
	width:10%;
	margin-left:0.3%;
}
.controls li:first-child {
	margin-left:0;
}
.controls .progress {
	width:38%;
	cursor:pointer;
}
.controls button {
	width:100%;
	text-align:center;
	overflow:hidden;
	white-space:nowrap;
  	text-overflow:ellipsis;
}
.controls progress {
	display:block;
	width:100%;
	height:20px;
	height:1.25rem;
	margin-top:2px;
	margin-top:0.125rem;
	border:1px solid #aaa;
	overflow:hidden;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;
	border-radius:5px;
}
.controls progress span {
	width:0%;
	height:100%;
	display:inline-block;
	background-color:#2a84cd;	
}

/* fullscreen */
html:-ms-fullscreen {
	width:100%;
}
:-webkit-full-screen {
	background-color:transparent;
}
/* hide controls on fullscreen with WebKit */
figure[data-fullscreen=true] video::-webkit-media-controls {
	display:none !important;
}
figure[data-fullscreen=true] {
	max-width:100%;
	width:100%;
	margin:0;
	padding:0;
}
figure[data-fullscreen=true] video {
	height:auto;
}
figure[data-fullscreen=true] figcaption {
	display:none;
}
figure[data-fullscreen=true] .controls {
	position:absolute;
	bottom:2%;
	width:100%;
	z-index:2147483647;
}
figure[data-fullscreen=true] .controls li {
	width:5%;
}
figure[data-fullscreen=true] .controls .progress {
	width:68%;
}
</style>
<figure id="videoContainer" data-fullscreen="false">
	<video id="video" preload="metadata" poster="/images/poster.jpg">
		<source src="/video/tears-of-steel-battle-clip-medium.mp4" type="video/mp4">
		<source src="/video/tears-of-steel-battle-clip-medium.webm" type="video/webm">
		<source src="/video/tears-of-steel-battle-clip-medium.ogg" type="video/ogg">
		<!-- Flash fallback -->
		<object type="application/x-shockwave-flash" data="flash-player.swf?videoUrl=/video/tears-of-steel-battle-clip-medium.mp4" width="1024" height="576">
			<param name="movie" value="flash-player.swf?videoUrl=/video/tears-of-steel-battle-clip-medium.mp4">
			<param name="allowfullscreen" value="true">
			<param name="wmode" value="transparent">
			<param name="flashvars" value="controlbar=over&amp;image=/images/poster.jpg&amp;file=flash-player.swf?videoUrl=/video/tears-of-steel-battle-clip-medium.mp4">
			<img alt="Tears of Steel poster image" src="/images/poster.jpg" width="1024" height="428" title="No video playback possible, please download the video from the link below">
		</object>
		<!-- Offer download -->
		<a href="/video/tears-of-steel-battle-clip-medium.mp4">Download MP4</a>
	</video>
	<ul id="video-controls" class="controls" style="display: block;">
		<li><button id="playpause" type="button">Play/Pause</button></li>
		<li><button id="stop" type="button">Stop</button></li>
		<li class="progress">
			<progress id="progress" value="0" min="0" max="70.542222">
				<span id="progress-bar" style="width: 0%;"></span>
			</progress>
		</li>
		<li><button id="mute" type="button">Mute/Unmute</button></li>
		<li><button id="volinc" type="button">Vol+</button></li>
		<li><button id="voldec" type="button">Vol-</button></li>
		<li><button id="fs" type="button">Fullscreen</button></li>
	</ul>
	<figcaption>
		© Blender Foundation | <a href="http://mango.blender.org">mango.blender.org</a>
	</figcaption>
</figure>

<script src="<?php echo $this->baseUrl('/js/video-player.js'); ?>"></script>