<div class="col-md-12 no-padding">
    <div id="webtv" class="fp3" data-id='<?php echo $this->existing->id;?>'> </div>
    <div class="row holder">
        <div class="video-main-info col-xs-12">
            <div class="title-wrapper col-xs-8">
                <h1 class="video-main-title"><?php echo $this->existing->title;?></h1>
            </div>
            <div class="col-xs-4">
                <input id="fake-rating" type="number" class="rating" min=0 max=5 step=1 value=<?php echo $this->existing->rating?> data-size="sm">
            </div>
        </div>
        <div class="video-main-info col-xs-12">
            <div class="title-wrapper col-xs-8">
                <p class="video-main-user">
                    <?php foreach($this->existing->tags as $one_tag){?>
                        <span class="label label-default"><?php echo $one_tag;?></span>
                    <?php }?>
                </p>
            </div>
            <div class="col-xs-4">
                <span class="video-main-plays"><?php echo $this->existing->view_count;?> views</span>
            </div>
        </div>
     </div>

    <?php foreach ($this->videos as $video) {
        if($video->id == $this->existing->id){
            continue;
        }
        $video_url = $this->url(array('module' => 'default', 'controller' => 'content', 'action' => 'video', 'id' => $video->id,'cat_id' => $this->cat_id), 'default', true);
    ?>
    <div class="row holder">
        <div class="col-sm-5 col-xs-5 img-container">
            <a href="<?php echo $video_url;?>" class="video-link">
                <img class="video-image" src="<?php echo $video->thumb_url; ?>">
                <!--div class="badge badge-duration"><?php //echo gmdate("H:i:s", $video->duration);?></div-->
                <div class="play small"></div>
                <div class="logo-hd"><img src="/images/hd-logo.png"></div>
            </a>
        </div>
        <div class="col-sm-7 col-xs-7">
            <div class="col-xs-12">
                <a class="video-link" href="<?php echo $video_url; ?>">
                    <p class="video-info-title"><?php echo $video->title; ?></p>
                </a>
            </div>
            <div class="col-xs-12 video-info-tags">
                <?php foreach(explode(',', $video->tags) as $one_tag){?>
                    <span class="label label-default"><?php echo $one_tag;?></span>
                <?php }?>
            </div>
            <div class="col-xs-12">
                <div class="col-xs-5 star-rating-holder">
                    <input id="fake-rating" type="number" class="rating smallest" min=0 max=5 step=1 value=<?php echo $video->rating?> data-size="xs">
                </div>
                <div class="col-xs-7">
                    <span class="video-date"><?php echo $video->view_count.' views';?></span>
                </div>
            </div>
            
        </div>
    </div>
    <?php } ?>
</div>
<script>
var content_object = <?php echo json_encode($this->existing);?>;
</script>