<p>CUSTOMER SUPPORT</p>

<p>This page covers some of the more common questions you may have and problems you might encounter while using our site, but if you still can&#39;t find an answer to your question/problem here, make sure you contact us as soon as possible using our Contact Page.</p>

<p><br />
&nbsp;</p>

<p>Billing Accounts</p>

<p>FREQUENTLY ASKED QUESTIONS￼ Apollo 11</p>

<p><br />
&nbsp;</p>

<p>Apollo 11 was the spaceflight that landed the first humans, Americans Neil Armstrong and Buzz Aldrin, on the Moon on July 20, 1969, at 20:18 UTC. Armstrong became the first to step onto the lunar surface 6 hours later on July 21 at 02:56 UTC.</p>

<p><br />
&nbsp;</p>

<p>Armstrong spent about three and a half two and a half hours outside the spacecraft, Aldrin slightly less; and together they collected 47.5 pounds (21.5&nbsp;kg) of lunar material for return to Earth. A third member of the mission, Michael Collins, piloted the command spacecraft alone in lunar orbit until Armstrong and Aldrin returned to it for the trip back to Earth.</p>

<p><br />
&nbsp;</p>

<p>Broadcasting and quotes ￼</p>

<p><br />
&nbsp;</p>

<p>Broadcast on live TV to a world-wide audience, Armstrong stepped onto the lunar surface and described the event as:</p>

<p><br />
&nbsp;</p>

<p>One small step for [a] man, one giant leap for mankind.</p>

<p><br />
&nbsp;</p>

<p>Apollo 11 effectively ended the Space Race and fulfilled a national goal proposed in 1961 by the late U.S. President John F. Kennedy in a speech before the United States Congress:</p>

<p><br />
&nbsp;</p>

<p>[...] before this decade is out, of landing a man on the Moon and returning him safely to the Earth.</p>

<p><br />
&nbsp;</p>

<p>Technical details ￼</p>

<p><br />
&nbsp;</p>

<p>Mission crew</p>

<p>Position Astronaut</p>

<p>Commander Neil A. Armstrong</p>

<p>Command Module Pilot Michael Collins</p>

<p>Lunar Module Pilot Edwin &quot;Buzz&quot; E. Aldrin, Jr.</p>

<p>Launched by a Saturn V rocket from Kennedy Space Center in Merritt Island, Florida on July 16, Apollo 11 was the fifth manned mission of NASA&#39;s Apollo program. The Apollo spacecraft had three parts:</p>

<p><br />
&nbsp;</p>

<p>Command Module with a cabin for the three astronauts which was the only part which landed back on Earth</p>

<p>Service Module which supported the Command Module with propulsion, electrical power, oxygen and water</p>

<p>Lunar Module for landing on the Moon.</p>

<p>After being sent to the Moon by the Saturn V&#39;s upper stage, the astronauts separated the spacecraft from it and travelled for three days until they entered into lunar orbit. Armstrong and Aldrin then moved into the Lunar Module and landed in the Sea of Tranquility. They stayed a total of about 21 and a half hours on the lunar surface. After lifting off in the upper part of the Lunar Module and rejoining Collins in the Command Module, they returned to Earth and landed in the Pacific Ocean on July 24.</p>

<p><br />
&nbsp;</p>

<p>Source: Wikipedia.org</p>

<p>1. WHAT IS http://xtcprime.com</p>

<p><a href="http://fappexxx.golive.rs">http://xtcprime.com</a> is home to entire library of movies. We offer exclusive access to our members to large library of movies and adult content.</p>

<p><br />
&nbsp;</p>

<p><a name="_GoBack"></a> 2. How to subscribe to <a href="http://fappexxx.golive.rs">http://xtcprime.com</a></p>

<p>ToDO SegPay</p>

<p><br />
&nbsp;</p>

<p>3. I&#39;M CONCERNED ABOUT MY PRIVACY, HOW WILL I BE BILLED?</p>

<p>A discreet charge shown as &quot;Telecorpllc&quot; will appear on your account statement. The site name and link won&#39;t appear. The data that was recorded when you signed up is used by our tech support to contact you (by email only) and we won&#39;t ever sell or give away your personal information or send any mail to your postal address.</p>

<p><br />
&nbsp;</p>

<p>4. IS THE FEE FOR http://xtcprime.com MONTHLY?</p>

<p>ToDo It is &hellip;</p>

<p><br />
&nbsp;</p>

<p>5. HOW LONG DO I HAVE OT WAIT UNTILL MY LOGIN WORKS FOR THE MEMBERS AREA?</p>

<p>You&#39;ll just have to wait for between 2 and 5 little minutes for your username/password to be propagated on all our servers. If after 10/15 minutes your account doesn&#39;t work, just contact us through our contact information page - make sure you tell us as much info as possible so we can fix the problem quickly!</p>

<p><br />
&nbsp;</p>

<p>6. I DIDN&#39;T RECEIVE MY LOGIN INFORMATION, WHAT CAN I DO?</p>

<p>If you didn&#39;t receive an email with your access information after signing up, you have to contact us as soon as possible so we can send you your access to get into the members area - you can contact us through our contact page.</p>

<p><br />
&nbsp;</p>

<p>7. MY SCCSESS ISN&#39;T WOTKING, HOW CAN I GET IT FIXED?</p>

<p>Sometimes, it happens that an login/pass doesn&#39;t work to access the Members Area. If you have that problem, first make sure you&#39;re typing the good username and password. It can get tricky sometimes, you could type a L (l) instead of 1 (one) etc. If it still doesn&#39;t work, contact us as soon as possible throught our contact page, make sure you fill the form entirely so we can help you as quickly as possible.</p>

<p><br />
&nbsp;</p>

<p>8. I LOST MY PASSWORD, HOW DO I RETREIVE IT?</p>

<p>To retreive your password, contact us as soon as possible through &hellip;</p>

<p><br />
&nbsp;</p>

<p>9. HOW DO I CANCEL MY MEMBERSHIP?</p>

<p>ToDO SegPay</p>
