<div class="main-content static">
<p><a name="_GoBack"></a> CUSTOMER SUPPORT INFORMATION (FAQ)</p>

<p>This page covers some of the more common questions you may have and problems you might encounter while using our site, but if you still can&#39;t find an answer to your question/problem here, make sure you contact us as soon as possible using our Contact Page.</p>

<p>
&nbsp;</p>

<p>Billing Accounts</p>

<p>FREQUENTLY ASKED QUESTIONS</p>

<p>1. WHAT IS http://xtcprime.com</p>

<p><a href="http://fappexxx.golive.rs">http://xtcprime.com</a> is home to entire library of movies. We offer exclusive access to our members to large library of movies and adult content.</p>

<p>
&nbsp;</p>

<p>2. How to subscribe to <a href="http://fappexxx.golive.rs">http://xtcprime.com</a></p>

<p>ToDO SegPay</p>

<p>
&nbsp;</p>

<p>2. I&#39;M CONCERNED ABOUT MY PRIVACY, HOW WILL I BE BILLED?</p>

<p>A discreet charge shown as &quot;segpaycs.com&quot; will appear on your account statement. The site name and link won&#39;t appear. The data that was recorded when you signed up is used by our tech support to contact you (by email only) and we won&#39;t ever sell or give away your personal information or send any mail to your postal address.</p>

<p>
&nbsp;</p>

<p>3. IS THE FEE FOR http://xtcprime.com MONTHLY?</p>

<p>ToDo It is &hellip;</p>

<p>
&nbsp;</p>

<p>4. HOW LONG DO I HAVE OT WAIT UNTILL MY LOGIN WORKS FOR THE MEMBERS AREA?</p>

<p>You&#39;ll just have to wait for between 2 and 5 little minutes for your username/password to be propagated on all our servers. If after 10/15 minutes your account doesn&#39;t work, just contact us through our contact information page - make sure you tell us as much info as possible so we can fix the problem quickly!</p>

<p>
&nbsp;</p>

<p>5. I DIDN&#39;T RECEIVE MY LOGIN INFORMATION, WHAT CAN I DO?</p>

<p>If you didn&#39;t receive an email with your access information after signing up, you have to contact us as soon as possible so we can send you your access to get into the members area - you can contact us through our contact page.</p>

<p>
&nbsp;</p>

<p>6. MY SCCSESS ISN&#39;T WOTKING, HOW CAN I GET IT FIXED?</p>

<p>Sometimes, it happens that an login/pass doesn&#39;t work to access the Members Area. If you have that problem, first make sure you&#39;re typing the good username and password. It can get tricky sometimes, you could type a L (l) instead of 1 (one) etc. If it still doesn&#39;t work, contact us as soon as possible throught our contact page, make sure you fill the form entirely so we can help you as quickly as possible.</p>

<p>
&nbsp;</p>

<p>7. I LOST MY PASSWORD, HOW DO I RETREIVE IT?</p>

<p>To retreive your password, contact us as soon as possible through &hellip;</p>

<p>
&nbsp;</p>

<p>8. HOW DO I CANCEL MY MEMBERSHIP?</p>

<p>ToDO SegPay</p>

</div>
